<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $INGINF_Subjects = [
            ['code' => 'LEN-113', 'name' => 'Lenguaje y Comunicación I', 'uc' => 3, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-113', 'name' => 'Inglés I', 'uc' => 3, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'INF-102', 'name' => 'Informática Básica', 'uc' => 2, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CAL-114', 'name' => 'Cálculo I', 'uc' => 4, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CIE-102', 'name' => 'Ciencia e Ingeniería', 'uc' => 2, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'LOG-103', 'name' => 'Lógica', 'uc' => 3, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TID-102', 'name' => 'Técnicas de Inv. Documental', 'uc' => 2, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'DPT-102', 'name' => 'Deporte', 'uc' => 2, 'semester' => 1, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'LEN-223', 'name' => 'Lenguaje y Comunicación II', 'uc' => 3, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-223', 'name' => 'Inglés II', 'uc' => 3, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ALG-203', 'name' => 'Algebra Lineal', 'uc' => 3, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CAL-224', 'name' => 'Cálculo II', 'uc' => 4, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'FIS-214', 'name' => 'Física I', 'uc' => 4, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'OAE-202', 'name' => 'Org. y Adm. de Empresas', 'uc' => 2, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'EDD-203', 'name' => 'Estructura de Datos', 'uc' => 3, 'semester' => 2, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-333', 'name' => 'Inglés III', 'uc' => 3, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'LAF-312', 'name' => 'Laboratorio de Física I', 'uc' => 2, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CAL-334', 'name' => 'Cálculo III', 'uc' => 4, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'FIS-324', 'name' => 'Física II', 'uc' => 4, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'MAT-302', 'name' => 'Matemática Discreta', 'uc' => 2, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'BDD-304', 'name' => 'Base de Datos', 'uc' => 4, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TEC-303', 'name' => 'Teoria Económica', 'uc' => 3, 'semester' => 3, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-443', 'name' => 'Inglés IV', 'uc' => 3, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'LAF-422', 'name' => 'Laboratorio de Física II', 'uc' => 2, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CAL-444', 'name' => 'Cálculo IV', 'uc' => 4, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'FDR-403', 'name' => 'Fundamentos de Redes', 'uc' => 3, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TDG-414', 'name' => 'Tecnología Digital I', 'uc' => 4, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRO-413', 'name' => 'Programación I', 'uc' => 3, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ADC-403', 'name' => 'Arquitectura del Computador', 'uc' => 3, 'semester' => 4, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-553', 'name' => 'Inglés V', 'uc' => 3, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'LAD-502', 'name' => 'Laboratorio de Datos', 'uc' => 2, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'SSC-502', 'name' => 'Servicio Social Comunitario', 'uc' => 2, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'EYP-503', 'name' => 'Estadística y Probabilidad', 'uc' => 3, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TDG-524', 'name' => 'Tecnología Digital II', 'uc' => 4, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRO-523', 'name' => 'Programación II', 'uc' => 3, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'SOP-513', 'name' => 'Sistemas Operativos I', 'uc' => 3, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'RYT-502', 'name' => 'Seminario de Redes', 'uc' => 2, 'semester' => 5, 'specialization_id' => 1, 'type' => 'Obligatoria'],
            ['code' => 'GDT-502', 'name' => 'Seminario de Gestión de Datos', 'uc' => 2, 'semester' => 5, 'specialization_id' => 4, 'type' => 'Obligatoria'],
            ['code' => 'SSI-502', 'name' => 'Seminario de Seg. Informática', 'uc' => 2, 'semester' => 5, 'specialization_id' => 2, 'type' => 'Obligatoria'],
            ['code' => 'SAP-502', 'name' => 'Seminario de Automatización', 'uc' => 2, 'semester' => 5, 'specialization_id' => 3, 'type' => 'Obligatoria'],
            ['code' => 'TYD-502', 'name' => 'Teorías y Técnicas de Decisión', 'uc' => 2, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'OYP-502', 'name' => 'Org. y Prog. del Trabajo', 'uc' => 2, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'GRH-502', 'name' => 'Gestión de Relaciones Humanas', 'uc' => 2, 'semester' => 5, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'ING-663', 'name' => 'Inglés VI', 'uc' => 3, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'SOP-623', 'name' => 'Sistemas Operativos II', 'uc' => 3, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ISF-614', 'name' => 'Ingeniería del Software I', 'uc' => 4, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRO-633', 'name' => 'Programación III', 'uc' => 3, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CAL-604', 'name' => 'Cálculo Numérico', 'uc' => 4, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'MEI-612', 'name' => 'Metodología de la Investigación I', 'uc' => 2, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'RCB-613', 'name' => 'Redes Cableadas I', 'uc' => 3, 'semester' => 6, 'specialization_id' => 1, 'type' => 'Obligatoria'],
            ['code' => 'TCS-603', 'name' => 'Tecnología Cliente/Servidor', 'uc' => 3, 'semester' => 6, 'specialization_id' => 4, 'type' => 'Obligatoria'],
            ['code' => 'ARD-603', 'name' => 'Análisis y Rec. Delitos Inf.', 'uc' => 3, 'semester' => 6, 'specialization_id' => 2, 'type' => 'Obligatoria'],
            ['code' => 'PGC-603', 'name' => 'Programación de Circuitos', 'uc' => 3, 'semester' => 6, 'specialization_id' => 3, 'type' => 'Obligatoria'],
            ['code' => 'RMM-602', 'name' => 'Reparación y Mant. de Micros', 'uc' => 2, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'DAC-602', 'name' => 'Diseño Asistido por Computador', 'uc' => 2, 'semester' => 6, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'ISF-724', 'name' => 'Ingeniería de Software II', 'uc' => 4, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRW-703', 'name' => 'Programación Web', 'uc' => 3, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ING-773', 'name' => 'Inglés VII', 'uc' => 3, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'MEI-722', 'name' => 'Metodología de la Inv. II', 'uc' => 2, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'IOP-703', 'name' => 'Investigación de Operaciones', 'uc' => 3, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'SDS-703', 'name' => 'Sistemas de Señales', 'uc' => 3, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'RCB-723', 'name' => 'Redes Cableadas II', 'uc' => 3, 'semester' => 7, 'specialization_id' => 1, 'type' => 'Obligatoria'],
            ['code' => 'SGD-703', 'name' => 'Seguridad de Datos', 'uc' => 3, 'semester' => 7, 'specialization_id' => 4, 'type' => 'Obligatoria'],
            ['code' => 'SIN-703', 'name' => 'Seguridad Informática', 'uc' => 3, 'semester' => 7, 'specialization_id' => 2, 'type' => 'Obligatoria'],
            ['code' => 'ELT-703', 'name' => 'Electrónica', 'uc' => 3, 'semester' => 7, 'specialization_id' => 3, 'type' => 'Obligatoria'],
            ['code' => 'TGR-702', 'name' => 'Técnicas Gerenciales', 'uc' => 2, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'SAU-702', 'name' => 'Sistemas Automatizados', 'uc' => 2, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'ARH-702', 'name' => 'Adm. de Recursos Humanos', 'uc' => 2, 'semester' => 7, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'FEP-803', 'name' => 'Formulación de Proyectos', 'uc' => 3, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'IEN-803', 'name' => 'Ingeniería Económica', 'uc' => 3, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'FDD-802', 'name' => 'Fundamentos del derecho', 'uc' => 2, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TRD-814', 'name' => 'Transmisión de Datos I', 'uc' => 4, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'CTB-803', 'name' => 'Contabilidad General', 'uc' => 3, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRE-803', 'name' => 'Programación Emergente', 'uc' => 3, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'RIB-813', 'name' => 'Redes Inalámbricas I', 'uc' => 3, 'semester' => 8, 'specialization_id' => 1, 'type' => 'Obligatoria'],
            ['code' => 'ABD-813', 'name' => 'Administración de BD I', 'uc' => 3, 'semester' => 8, 'specialization_id' => 4, 'type' => 'Obligatoria'],
            ['code' => 'CRP-803', 'name' => 'Criptografía', 'uc' => 3, 'semester' => 8, 'specialization_id' => 2, 'type' => 'Obligatoria'],
            ['code' => 'MET-803', 'name' => 'Mecatrónica', 'uc' => 3, 'semester' => 8, 'specialization_id' => 3, 'type' => 'Obligatoria'],
            ['code' => 'SAM-802', 'name' => 'Seguridad y Medio Ambiente', 'uc' => 2, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'PRD-802', 'name' => 'Producción', 'uc' => 2, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'MAD-802', 'name' => 'Modelos Administrativos', 'uc' => 2, 'semester' => 8, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'AUS-904', 'name' => 'Auditoria de Sistemas', 'uc' => 4, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'ETP-902', 'name' => 'Ética Profesional', 'uc' => 2, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TEL-903', 'name' => 'Transacciones Electrónicas', 'uc' => 3, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'TRD-924', 'name' => 'Transmisión de Datos II', 'uc' => 4, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'PRO-903', 'name' => 'Programación Multimedia', 'uc' => 3, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'STG-903', 'name' => 'Sem. de Trabajo de Grado', 'uc' => 3, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
            ['code' => 'RIB-923', 'name' => 'Redes Inalámbricas II', 'uc' => 3, 'semester' => 9, 'specialization_id' => 1, 'type' => 'Obligatoria'],
            ['code' => 'ABD-923', 'name' => 'Administración de BD II', 'uc' => 3, 'semester' => 9, 'specialization_id' => 4, 'type' => 'Obligatoria'],
            ['code' => 'AFO-903', 'name' => 'Análisis Forense', 'uc' => 3, 'semester' => 9, 'specialization_id' => 2, 'type' => 'Obligatoria'],
            ['code' => 'CPI-903', 'name' => 'Control de Proc. Industriales', 'uc' => 3, 'semester' => 9, 'specialization_id' => 3, 'type' => 'Obligatoria'],
            ['code' => 'RPV-902', 'name' => 'VPN Redes Privadas Virtuales', 'uc' => 2, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'DCM-902', 'name' => 'Diseño y Control de Modelos', 'uc' => 2, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'CEP-902', 'name' => 'Control Estad. de Procesos', 'uc' => 2, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'TLP-902', 'name' => 'Teoría de Leng. de Prog.', 'uc' => 2, 'semester' => 9, 'specialization_id' => NULL, 'type' => 'Electiva'],
            ['code' => 'PAP-10020', 'name' => 'Pasantías Profesionales', 'uc' => 20, 'semester' => 10, 'specialization_id' => NULL, 'type' => 'Obligatoria'],
        ];

        DB::table('subjects')->insert($INGINF_Subjects);
    }
}
